// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TamburelloDavideMusicManager.Data;

#nullable disable

namespace TamburelloDavideMusicManager.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251124193339_AggiuntaStrumenti")]
    partial class AggiuntaStrumenti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Abilita", b =>
                {
                    b.Property<int>("CantanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrumentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Livello")
                        .HasColumnType("INTEGER");

                    b.HasKey("CantanteId", "StrumentoId");

                    b.HasIndex("StrumentoId");

                    b.ToTable("Abilita");
                });

            modelBuilder.Entity("Strumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Strumento");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Cantante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtichettaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeReale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EtichettaId");

                    b.ToTable("Cantanti");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Esibizione", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdineUscita")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotiGiuria")
                        .HasColumnType("INTEGER");

                    b.HasKey("FestivalId", "CantanteId");

                    b.HasIndex("CantanteId");

                    b.ToTable("Esibizioni");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Etichetta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SedeLegale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etichette");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Festival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Festival");
                });

            modelBuilder.Entity("Abilita", b =>
                {
                    b.HasOne("TamburelloDavideMusicManager.Model.Cantante", "Cantante")
                        .WithMany("Abilita")
                        .HasForeignKey("CantanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Strumento", "Strumento")
                        .WithMany("Abilita")
                        .HasForeignKey("StrumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cantante");

                    b.Navigation("Strumento");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Cantante", b =>
                {
                    b.HasOne("TamburelloDavideMusicManager.Model.Etichetta", "Etichetta")
                        .WithMany("Cantanti")
                        .HasForeignKey("EtichettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etichetta");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Esibizione", b =>
                {
                    b.HasOne("TamburelloDavideMusicManager.Model.Cantante", "Cantante")
                        .WithMany("Esibizioni")
                        .HasForeignKey("CantanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TamburelloDavideMusicManager.Model.Festival", "Festival")
                        .WithMany("Esibizioni")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cantante");

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("Strumento", b =>
                {
                    b.Navigation("Abilita");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Cantante", b =>
                {
                    b.Navigation("Abilita");

                    b.Navigation("Esibizioni");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Etichetta", b =>
                {
                    b.Navigation("Cantanti");
                });

            modelBuilder.Entity("TamburelloDavideMusicManager.Model.Festival", b =>
                {
                    b.Navigation("Esibizioni");
                });
#pragma warning restore 612, 618
        }
    }
}
